#include <Arduino.h>
#include "helpers.h"
#include "file_system.h" 
#include "motionsensor.h"
#include "network.h"
#include "arduino_secrets.h" 
#include "thsensor.h"
#include "camera.h"
#include <SPI.h>
#include "logger.h"