#include <Arduino.h>
#include "file_system.h" 
#include "logger.h"
#include "motionsensor.h"
#include "wifi.h"
#include "WiFiS3.h"
#include "arduino_secrets.h" 
#include "thsensor.h"
#include "camera.h"
